name: first workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: fetch the repo
        uses: actions/checkout@main
      - name: run shell script
        run: |
          chmod +x wf1.sh
          ./wf1.sh
     