name: first workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install cowsay
        run: sudo apt get install cowsay -y

      - name: write cowsay to file 
        run: cowsay "Hello from the runner!" > output.txt

      - name: sleep for 10 seconds
        run: sleep 10
  test:
    runs-on: ubuntu-latest
  deploy:
    runs-on: ubuntu-latest
