name: Discover Varibales and secrets
on: push
jobs:
  docker_job:
    runs-on: ubuntu-latest
    steps:
      - name: docker build
        run: docker build
      - name: docker login
        run: docker login
      - name: docker publish
        run: docker publish
  deploy_job:
    needs: docker_job
    runs-on: ubuntu-latest
    steps:
      - name: docker build
        run: docker build
      - name: docker login
        run: docker login
      - name: docker publish
        run: docker publish